#pragma once
// Auto-generated by tools/embed_lib.py — do not edit by hand.
#include <string>
namespace vesna {
static const std::string kEmbeddedLib_csv = R"VESLIB_1_7(/* Vesna 标准库：csv.ves */

def csv_parse(text)-
-lines = #split(text; "\n")
-rows = []
-for line in lines-
--if #len(line) > '0'-
---#append(rows; #split(line; ","))
-back(rows)

def csv_write(rows)-
-out = ""
-for row in rows-
--out = out + #join(row; ",") + "\n"
-back(out))VESLIB_1_7";
static const std::string kEmbeddedLib_json = R"VESLIB_1_7(/* Vesna 标准库：json.ves */

def json_parse(text)-
-chars = []
-for c in text-
--#append(chars; c)
-state = [chars; '1'; #len(chars)]
-back(json_value(state))

def json_peek(st)-
-if st['2'] > st['3']-
--back("")
-back(st['1'][st['2']])

def json_next(st)-
-st['2'] += '1'

def json_skip_ws(st)-
-while st['2'] <= st['3']-
--c = st['1'][st['2']]
--if c == " " or c == "\t" or c == "\n" or c == "\r"-
---st['2'] += '1'
--else-
---break

def json_value(st)-
-json_skip_ws(st)
-c = json_peek(st)
-if c == "{"-
--back(json_object(st))
-if c == "["-
--back(json_array(st))
-if c == "\""-
--back(json_string(st))
-if c == "t"-
--json_literal(st; "true")
--back(true)
-if c == "f"-
--json_literal(st; "false")
--back(false)
-if c == "n"-
--json_literal(st; "null")
--back(none)
-back(json_number(st))

def json_literal(st; word)-
-i = '1'
-while i <= #len(word)-
--json_next(st)
--i += '1'

def json_string(st)-
-json_skip_ws(st)
-json_next(st)
-out = ""
-while st['2'] <= st['3']-
--c = json_peek(st)
--json_next(st)
--if c == "\""-
---back(out)
--if c == "\\"-
---e = json_peek(st)
---json_next(st)
---if e == "n"-
----out = out + "\n"
---elif e == "t"-
----out = out + "\t"
---elif e == "r"-
----out = out + "\r"
---elif e == "\""-
----out = out + "\""
---elif e == "\\"-
----out = out + "\\"
---else-
----out = out + e
--else-
---out = out + c
-back(out)

def json_number(st)-
-json_skip_ws(st)
-start = st['2']
-while st['2'] <= st['3']-
--c = st['1'][st['2']]
--if c == "-" or c == "+" or c == "." or c == "e" or c == "E"-
---st['2'] += '1'
--elif c >= "0" and c <= "9"-
---st['2'] += '1'
--else-
---break
-num_str = ""
-i = start
-while i < st['2']-
--num_str = num_str + st['1'][i]
--i += '1'
-if #find(num_str; ".") > '0'-
--back(#float(num_str))
-if #find(num_str; "e") > '0'-
--back(#float(num_str))
-back(#int(num_str))

def json_object(st)-
-json_skip_ws(st)
-json_next(st)
-obj = {}
-json_skip_ws(st)
-if json_peek(st) == "}"-
--json_next(st)
--back(obj)
-while true-
--json_skip_ws(st)
--k = json_string(st)
--json_skip_ws(st)
--json_next(st)
--v = json_value(st)
--obj[k] = v
--json_skip_ws(st)
--c = json_peek(st)
--if c == ","-
---json_next(st)
---continue
--json_next(st)
--back(obj)

def json_array(st)-
-json_skip_ws(st)
-json_next(st)
-arr = []
-json_skip_ws(st)
-if json_peek(st) == "]"-
--json_next(st)
--back(arr)
-while true-
--v = json_value(st)
--#append(arr; v)
--json_skip_ws(st)
--c = json_peek(st)
--if c == ","-
---json_next(st)
---continue
--json_next(st)
--back(arr)

def json_write(v)-
-back(json_ser(v))

def json_ser(v)-
-t = #type(v)
-if t == "none"-
--back("null")
-if t == "bool"-
--if v-
---back("true")
--back("false")
-if t == "int"-
--back(#str(v))
-if t == "float"-
--back(#str(v))
-if t == "str"-
--back(json_esc(v))
-if t == "list"-
--back(json_arr(v))
-if t == "group"-
--back(json_arr(v))
-if t == "dict"-
--back(json_obj(v))
-back("null")

def json_esc(s)-
-out = "\""
-for c in s-
--if c == "\""-
---out = out + "\\\""
--elif c == "\\"-
---out = out + "\\\\"
--elif c == "\n"-
---out = out + "\\n"
--elif c == "\t"-
---out = out + "\\t"
--elif c == "\r"-
---out = out + "\\r"
--else-
---out = out + c
-back(out + "\"")

def json_arr(v)-
-out = "["
-first = true
-for item in v-
--if not first-
---out = out + ","
--first = false
--out = out + json_ser(item)
-back(out + "]")

def json_obj(d)-
-out = "{"
-first = true
-ks = #keys(d)
-for k in ks-
--if not first-
---out = out + ","
--first = false
--out = out + json_esc(k) + ":" + json_ser(d[k])
-back(out + "}"))VESLIB_1_7";
static const std::string kEmbeddedLib_pkg = R"VESLIB_1_7(/* Vesna 包管理器（vpm）—— vesna --pkg
   1.3.0：元数据校验、sha256 完整性、依赖自动安装、路径与伪装校验 */

import json,

args = #args(),
home = #getenv("VESNA_HOME"),
if home == ""-
-home = "C:\\Vesna",
pkgs = home + "\\packages",
reg_file = home + "\\registry.json",
default_reg = "https://youakasakura-YAS.github.io/vesna-pkg/registry.json",
MAX_DEPTH = '5',

/* ---------- 工具 ---------- */

def pkg_help()-
-print("Vesna 包管理器 vpm"),
-print("用法: vesna --pkg <命令> [参数]"),
-print("  init [名称]             初始化当前目录为包（名称默认 mypkg）"),
-print("  install <源>            安装包（目录 / zip / owner:repo / registry 包名）"),
-print("  remove <名称>           卸载包（--force 忽略依赖检查）"),
-print("  list                    列出已安装包"),
-print("  search <关键词>         搜索 registry 索引"),
-print("  registry <URL>          更新 registry 索引缓存"),
-print("  publish                打包并生成 registry 条目（zip + sha256）"),

def read_json(path)-
-if not #fexists(path)-
--back(none),
-t = #fread(path),
-try-
--back(json_parse(t)),
-catch e-
--print("  JSON 解析失败: " + path),
--back(none),

def err(msg)-
-print("  错误: " + msg),
-back(false),

def is_valid_name(n)-
-back(#match(n; "^[a-z][a-z0-9_-]+$")),

def is_valid_version(v)-
-back(#match(v; "^[0-9]+\\.[0-9]+\\.[0-9]+$")),

def cmp_versions(a; b)-
-/* 返回 -1 / 0 / 1，按三段数字比较 */
-ap = #split(a; "."),
-bp = #split(b; "."),
-if #len(ap) < '3' or #len(bp) < '3'-
--back('0'),
-for i in ['1';'2';'3']-
--ai = #int(ap[i]),
--bi = #int(bp[i]),
--if ai < bi-
---back('-1'),
--if ai > bi-
---back('1'),
-back('0'),

def version_satisfies(have; want)-
-/* have >= want */
-if cmp_versions(have; want) >= '0'-
--back(true),
-back(false),

def walk_files(dir)-
-/* 递归列出全部文件绝对路径 */
-out = [],
-entries = #ls(dir),
-for e in entries-
--if e == "." or e == ".."-
---continue,
--full = dir + "\\" + e,
--if #is_dir(full)-
---sub = walk_files(full),
---for f in sub-
----#append(out; f),
--else-
---#append(out; full),
-back(out),

def check_zip_safety(dir)-
-/* zip 解压后路径穿越防护：拒绝含 .. 或盘符的相对路径条目 */
-files = walk_files(dir),
-for f in files-
--rel = #sub(f; #len(dir) + '2'; #len(f)),
--if #find(rel; "..") != '0'-
---back(err("zip 包含不安全路径（..）: " + rel + " —— 已中止并清理")),
--if #find(rel; ":") != '0'-
---back(err("zip 包含绝对路径条目: " + rel + " —— 已中止并清理")),
-back(true),

def validate_registry(reg)-
-/* registry 索引结构校验 */
-if reg == none or #type(reg) != "list"-
--back(false),
-for pkg in reg-
--if #type(pkg) != "dict"-
---back(false),
--if not #has_key(pkg; "name") or #type(pkg["name"]) != "str"-
---back(false),
--if not #has_key(pkg; "url") or #type(pkg["url"]) != "str"-
---back(false),
-back(true),

def validate_meta(meta; base_dir)-
-/* 元数据校验：name / version / entry / dependencies */
-if meta == none or #type(meta) != "dict"-
--back(err("源不是 Vesna 包（缺少有效的 vesna-pkg.json）")),
-if not #has_key(meta; "name") or #type(meta["name"]) != "str" or not is_valid_name(meta["name"])-
--back(err("vesna-pkg.json 的 name 缺失或非法（须小写字母/数字/_-，如 my_pkg-1）")),
-if not #has_key(meta; "version") or #type(meta["version"]) != "str" or not is_valid_version(meta["version"])-
--back(err("vesna-pkg.json 的 version 缺失或非法（须 x.y.z）")),
-if #has_key(meta; "dependencies") and #type(meta["dependencies"]) != "dict"-
--back(err("vesna-pkg.json 的 dependencies 须为 dict")),
-if base_dir != "" and #has_key(meta; "entry")-
--entry = meta["entry"],
--if #type(entry) != "str"-
---back(err("vesna-pkg.json 的 entry 须为字符串")),
--if #find(entry; "..") != '0' or #find(entry; ":") != '0' or #find(entry; "/") != '0' or #find(entry; "\\") != '0'-
---back(err("entry 路径非法（不允许 .. / 盘符 / 目录分隔符）: " + entry)),
--if not #fexists(base_dir + "\\" + entry)-
---back(err("entry 文件不存在: " + entry)),
-back(true),

def check_dep_installed(name; want)-
-/* 返回 0=已满足 1=未安装 2=版本不足 */
-if not #fexists(pkgs + "\\" + name + "\\vesna-pkg.json")-
--back('1'),
-have = pkg_version_of(pkgs + "\\" + name),
-if want == "" or version_satisfies(have; want)-
--back('0'),
-back('2'),

def install_dep(dep_name; want)-
-/* 自动安装依赖：优先 registry，其次提示 */
-if #fexists(pkgs + "\\" + dep_name + "\\vesna-pkg.json")-
--back('0'),
-if install_by_name(dep_name; '1')-
--back('0'),
-back('-1'),

def pkg_version_of(dir)-
-meta = read_json(dir + "\\vesna-pkg.json"),
-if meta == none or #type(meta) != "dict" or not #has_key(meta; "version")-
--back("0.0.0"),
-back(meta["version"]),

def unzip(zip_path; dest_dir)-
-#mkdirs(dest_dir),
-plat = #platform(),
-if #find(plat; "windows") != '0'-
--#shell("powershell -NoProfile -Command \"Expand-Archive -Force -Path '" + zip_path + "' -DestinationPath '" + dest_dir + "'\""),
-else-
--#shell("tar -xf \"" + zip_path + "\" -C \"" + dest_dir + "\""),
-if #fexists(dest_dir + "\\vesna-pkg.json")-
--back(dest_dir),
-entries = #ls(dest_dir),
-for ent in entries-
--if #fexists(dest_dir + "\\" + ent + "\\vesna-pkg.json")-
---back(dest_dir + "\\" + ent),
-back(dest_dir),

def install_from_dir(src; depth)-
-meta = read_json(src + "\\vesna-pkg.json"),
-if not validate_meta(meta; src)-
--back(false),
-name = meta["name"],
-ver = meta["version"],
-print("  安装 " + name + " " + ver + " ..."),
-if depth > MAX_DEPTH-
--back(err("依赖嵌套过深（> " + MAX_DEPTH + " 层），疑似循环依赖")),
-/* 依赖处理 */
-if #has_key(meta; "dependencies")-
--deps = meta["dependencies"],
--for dep_name in #keys(deps)-
---want = "",
---if #type(deps[dep_name]) == "str"-
----want = deps[dep_name],
---st = check_dep_installed(dep_name; want),
---if st == '0'-
----print("  依赖 " + dep_name + " " + want + " 已满足"),
---elif st == '2'-
----print("  依赖 " + dep_name + " 已装版本不足（要求 " + want + "），尝试自动安装 ..."),
----if install_dep(dep_name; want) == '-1'-
-----print("    警告: 依赖 " + dep_name + " 自动安装失败，请手动处理"),
---else-
----print("  自动安装依赖 " + dep_name + " ..."),
----if install_dep(dep_name; want) == '-1'-
-----print("    警告: 依赖 " + dep_name + " 安装失败，请手动: vesna --pkg install <" + dep_name + " 的源>"),
-#mkdirs(pkgs),
-target = pkgs + "\\" + name,
-if #fexists(target)-
--print("  已存在 " + name + " " + pkg_version_of(target) + "，覆盖安装 ..."),
--#rmdir(target),
-#cpdir(src; target),
-if not #fexists(target + "\\vesna-pkg.json")-
--back(err("复制失败")),
-print("  完成: " + name + " " + ver),
-back(true),

def install_zip(zip_path; depth; expect_sha)-
-/* sha256 完整性校验 */
-if expect_sha != ""-
--got = #sha256(#bin_read(zip_path)),
--if got != expect_sha-
---back(err("sha256 校验失败（期望 " + expect_sha + "，实际 " + got + "）")),
-tmp = home + "\\packages\\_tmp",
-if #fexists(tmp)-
--#rmdir(tmp),
-#mkdirs(tmp),
-root = unzip(zip_path; tmp),
-if not check_zip_safety(tmp)-
--if #fexists(tmp)-
---#rmdir(tmp),
--back(false),
-ok = install_from_dir(root; depth),
-if #fexists(tmp)-
--#rmdir(tmp),
-back(ok),

def fetch_registry()-
-if #fexists(reg_file)-
--cached = read_json(reg_file),
--if validate_registry(cached)-
---back(cached),
--print("  警告: registry 缓存损坏或结构非法，重新下载 ..."),
--#fremove(reg_file),
-print("下载 registry 索引 ..."),
-#shell("curl -L -s -o \"" + reg_file + "\" \"" + default_reg + "\""),
-if #fexists(reg_file)-
--fresh = read_json(reg_file),
--if validate_registry(fresh)-
---back(fresh),
--print("错误: registry 索引无效（请检查网络或 URL，可手动: vesna --pkg registry <URL>）"),
--#fremove(reg_file),
--back(none),
-print("错误: registry 索引下载失败（可手动: vesna --pkg registry <URL>）"),
-back(none),

def install_by_name(name; depth)-
-if not is_valid_name(name)-
--print("  registry 中无此包或名称非法: " + name),
--back(false),
-reg = fetch_registry(),
-if reg == none or #type(reg) != "list"-
--back(false),
-for pkg in reg-
--if #type(pkg) == "dict" and #has_key(pkg; "name") and pkg["name"] == name-
---if not #has_key(pkg; "url")-
----print("  错误: registry 中 " + name + " 缺少 url"),
----back(false),
---expect_sha = "",
---if #has_key(pkg; "sha256") and #type(pkg["sha256"]) == "str"-
----expect_sha = pkg["sha256"],
---pver = "0.0.0",
---if #has_key(pkg; "version") and #type(pkg["version"]) == "str"-
----pver = pkg["version"],
---/* 本地缓存：命中且 sha256 匹配则离线安装 */
---cache_dir = home + "\\packages\\_cache",
---cached = cache_dir + "\\" + name + "-" + pver + ".zip",
---if #fexists(cached) and expect_sha != ""-
----c_sha = #sha256(#bin_read(cached)),
----if c_sha == expect_sha-
-----print("  命中本地缓存 " + name + "-" + pver + ".zip（sha256 匹配，离线安装）"),
-----ok = install_zip(cached; depth; expect_sha),
-----back(ok),
----print("  缓存 sha256 不匹配，重新下载 ..."),
---tmp_zip = home + "\\packages\\_tmp.zip",
---if #fexists(tmp_zip)-
----#fremove(tmp_zip),
---print("  下载 " + pkg["url"] + " ..."),
---#shell("curl -L -s -o \"" + tmp_zip + "\" \"" + pkg["url"] + "\""),
---if not #fexists(tmp_zip)-
----print("  错误: 下载失败（请检查网络或 registry URL）"),
----back(false),
---/* 缓存副本：仅当 sha256 已知且匹配时保留 */
---if expect_sha != ""-
----d_sha = #sha256(#bin_read(tmp_zip)),
----if d_sha == expect_sha-
-----#mkdirs(cache_dir),
-----#copy(tmp_zip; cached),
----print("  已缓存 " + name + "-" + pver + ".zip"),
---ok = install_zip(tmp_zip; depth; expect_sha),
---if #fexists(tmp_zip)-
----#fremove(tmp_zip),
---back(ok),
-print("  registry 中未找到包: " + name),
-print("  可先运行: vesna --pkg registry <URL> 更新索引"),
-back(false),

def install_git(src; depth)-
-tmp_zip = home + "\\packages\\_tmp.zip",
-if #fexists(tmp_zip)-
--#fremove(tmp_zip),
-url = "https://github.com/" + src + "/archive/refs/heads/main.zip",
-print("  下载 " + url + " ..."),
-#shell("curl -L -s -o \"" + tmp_zip + "\" \"" + url + "\""),
-if not #fexists(tmp_zip)-
--print("  错误: 下载失败（请确认源或网络）"),
--back(false),
-ok = install_zip(tmp_zip; depth; ""),
-if #fexists(tmp_zip)-
--#fremove(tmp_zip),
-back(ok),

if #len(args) < '1'-
-pkg_help(),
-#exit('0'),

cmd = args['1'],

if cmd == "init"-
-if #fexists("vesna-pkg.json")-
--print("错误: vesna-pkg.json 已存在"),
--#exit('1'),
-name = "mypkg",
-if #len(args) >= '2'-
--name = args['2'],
-if not is_valid_name(name)-
--print("错误: 名称非法（须小写字母/数字/_-，如 my_pkg-1）"),
--#exit('1'),
-tpl = "{\n  \"name\": \"" + name + "\",\n  \"version\": \"1.0.0\",\n  \"description\": \"\",\n  \"entry\": \"" + name + ".ves\",\n  \"dependencies\": {}\n}\n",
-#fwrite("vesna-pkg.json"; tpl),
-print("已生成 vesna-pkg.json（包名 " + name + "）"),
-#exit('0'),

if cmd == "install"-
-if #len(args) < '2'-
--print("用法: vesna --pkg install <目录|zip|owner:repo>"),
--#exit('1'),
-src = args['2'],
-if #fexists(src) and #is_dir(src)-
--if install_from_dir(src; '1') == false-
---#exit('1'),
-elif #fexists(src) and #is_file(src)-
--if install_zip(src; '1'; "") == false-
---#exit('1'),
-else-
--if install_by_name(src; '1') == false-
---if install_git(src; '1') == false-
----#exit('1'),
-#exit('0'),

if cmd == "remove"-
-if #len(args) < '2'-
--print("用法: vesna --pkg remove <名称>"),
--#exit('1'),
-name = args['2'],
-force = false,
-if #len(args) >= '3' and args['3'] == "--force"-
--force = true,
-target = pkgs + "\\" + name,
-if not #fexists(target)-
--print("未安装 " + name),
--#exit('0'),
-if not force-
--/* 检查被依赖 */
--deps_of = [],
--if #fexists(pkgs)-
---installed = #ls(pkgs),
---for other in installed-
----if other != name and other != "_tmp" and #fexists(pkgs + "\\" + other + "\\vesna-pkg.json")-
-----om = read_json(pkgs + "\\" + other + "\\vesna-pkg.json"),
-----if om != none and #type(om) == "dict" and #has_key(om; "dependencies") and #has_key(om["dependencies"]; name)-
------#append(deps_of; other),
--if #len(deps_of) > '0'-
---print("错误: 以下包仍依赖 " + name + ": " + #join(deps_of; ", ")),
---print("      如确要卸载请: vesna --pkg remove " + name + " --force"),
---#exit('1'),
-#rmdir(target),
-print("已卸载 " + name),
-#exit('0'),

if cmd == "list"-
-if not #fexists(pkgs)-
--print("（无已安装包）"),
--#exit('0'),
-names = #ls(pkgs),
-for name in names-
--if name != "_tmp" and #fexists(pkgs + "\\" + name + "\\vesna-pkg.json")-
---meta = read_json(pkgs + "\\" + name + "\\vesna-pkg.json"),
---entry = "",
---extra = "",
---if meta != none and #type(meta) == "dict" and #has_key(meta; "entry")-
----entry = meta["entry"],
----extra = "  entry=" + entry,
---print(name + " " + pkg_version_of(pkgs + "\\" + name) + extra),
--else-
---print(name + " （无元数据）"),
-#exit('0'),

if cmd == "search"-
-if #len(args) < '2'-
--print("用法: vesna --pkg search <关键词>"),
--#exit('1'),
-if not #fexists(reg_file)-
--print("registry 索引未缓存，正在下载默认索引 ..."),
--#shell("curl -L -s -o \"" + reg_file + "\" \"" + default_reg + "\""),
--if not #fexists(reg_file)-
---print("下载失败，请手动: vesna --pkg registry <URL>"),
---#exit('1'),
-reg = read_json(reg_file),
-if reg == none or #type(reg) != "list"-
--print("registry 索引无效"),
--#exit('1'),
-q = #down(args['2']),
-found = '0',
-for pkg in reg-
--if #type(pkg) == "dict"-
---pname = "",
---pdesc = "",
---pver = "0.0.0",
---if #has_key(pkg; "name")-
----pname = pkg["name"],
---if #has_key(pkg; "description")-
----pdesc = pkg["description"],
---if #has_key(pkg; "version")-
----pver = pkg["version"],
---if #find(#down(pname); q) != '0' or #find(#down(pdesc); q) != '0'-
----print(pname + " " + pver + " — " + pdesc),
----found = found + '1',
-print("找到 " + #str(found) + " 个"),
-#exit('0'),



if cmd == "publish"-
-if not #fexists("vesna-pkg.json")-
--print("错误: 当前目录不是包（缺少 vesna-pkg.json），先运行 init"),
--#exit('1'),
-meta = read_json("vesna-pkg.json"),
-if not validate_meta(meta; "")-
--#exit('1'),
-name = meta["name"],
-ver = meta["version"],
-entry = "",
-if #has_key(meta; "entry")-
--entry = meta["entry"],
-print("发布 " + name + " " + ver + "（entry=" + entry + "）"),
-/* 打包临时目录 */
-tmp = home + "\\packages\\_pub",
-if #fexists(tmp)-
--#rmdir(tmp),
-#mkdirs(tmp),
-#copy(entry; tmp + "\\" + entry),
-#copy("vesna-pkg.json"; tmp + "\\vesna-pkg.json"),
-zip_name = name + "-" + ver + ".zip",
-zip_path = #cwd() + "\\" + zip_name,
-plat = #platform(),
-if #find(plat; "windows") != '0'-
--#shell("powershell -NoProfile -Command \"Compress-Archive -Path '" + tmp + "\\*' -DestinationPath '" + zip_path + "' -Force\""),
-else-
--#shell("zip -rj \"" + zip_path + "\" \"" + tmp + "\""),
-if not #fexists(zip_path)-
--print("错误: 打包失败"),
--#exit('1'),
-checksum = #sha256(#bin_read(zip_path)),
-print("已生成 " + zip_name + "（sha256: " + checksum + "）"),
-/* registry 条目 */
-desc = "",
-if #has_key(meta; "description")-
--desc = meta["description"],
-desc = #replace(#replace(desc; "\n"; " "); "\""; "'"),
-lic = "MIT",
-if #has_key(meta; "license")-
--lic = meta["license"],
-deps_json = "{}",
-if #has_key(meta; "dependencies")-
--deps_json = #json_encode(meta["dependencies"]),
-entry_json = "{\n  \"name\": \"" + name + "\",\n  \"version\": \"" + ver + "\",\n  \"description\": \"" + desc + "\",\n  \"license\": \"" + lic + "\",\n  \"url\": \"https://youakasakura-YAS.github.io/vesna-pkg/packages/" + name + "/" + zip_name + "\",\n  \"checksum\": \"" + checksum + "\",\n  \"dependencies\": " + deps_json + "\n}",
-#fwrite("registry-entry.json"; entry_json),
-print("registry 条目已写入 registry-entry.json"),
-if #fexists("registry.json")-
--reg = read_json("registry.json"),
--if reg != none and #type(reg) == "list"-
---#append(reg; #json_decode(entry_json)),
---#fwrite("registry.json"; #json_encode(reg)),
---print("已更新本地 registry.json（" + #str(#len(reg)) + " 个条目）"),
-print("提示: 将 " + zip_name + " 放到 packages/" + name + "/，并把 registry-entry.json 内容并入 registry.json 后推送"),
-#exit('0'),

if cmd == "registry"-

-if #len(args) < '2'-
--url = default_reg,
--print("使用默认 registry: " + default_reg),
-else-
--url = args['2'],
-print("下载 registry 索引 ..."),
-#shell("curl -L -s -o \"" + reg_file + "\" \"" + url + "\""),
-if #fexists(reg_file)-
--print("已缓存 " + reg_file),
--#exit('0'),
-print("错误: 下载失败"),
-#exit('1'),

pkg_help(),)VESLIB_1_7";
static const std::string kEmbeddedLib_stat = R"VESLIB_1_7(/* Vesna 标准库：stat.ves */

def stat_count_by(items; key)-
-result = {}
-for item in items-
-val = item[key]
-if #has_key(result; val)-
--result[val] += '1'
-else-
--result[val] = '1'
-back(result)

def stat_unique(items)-
-seen = {}
-out = []
-for item in items-
-if not #has_key(seen; item)-
--seen[item] = true
--#append(out; item)
-back(out))VESLIB_1_7";
static const std::string kEmbeddedLib_text = R"VESLIB_1_7(/* Vesna 标准库：text.ves */

def text_word_count(s)-
-back(#len(#findall(s; "[^ \t\n\r]+")))

def text_extract_emails(s)-
-back(#findall(s; "[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}"))

def text_extract_urls(s)-
-back(#findall(s; "https?://[^ \t\n\r\"'<>]+"))

def text_extract_ips(s)-
-back(#findall(s; "\b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\b"))

def text_strip_html(s)-
-back(#gsub(s; "<[^>]+>"; ""))

def text_upper_first(s)-
-if #len(s) < '1'-
--back(s)
-back(#up(#char_at(s; '1')) + #sub(s; '2'; #str(#len(s))))

def text_reverse(s)-
-out = ""
-i = #len(s)
-while i >= '1'-
--out = out + #char_at(s; i)
--i -= '1'
-back(out))VESLIB_1_7";
inline std::string embeddedLib(const std::string& name) {
    if (name == "csv.ves") return kEmbeddedLib_csv;
    if (name == "json.ves") return kEmbeddedLib_json;
    if (name == "pkg.ves") return kEmbeddedLib_pkg;
    if (name == "stat.ves") return kEmbeddedLib_stat;
    if (name == "text.ves") return kEmbeddedLib_text;
    return "";
}
}
