# -*- coding: utf-8 -*-
"""生成 embedded_lib.h：把 lib/*.ves 嵌入 exe，实现单文件分发。
用法: python tools/embed_lib.py  （输出 src/cpp/embedded_lib.h）
"""
import io, os, re

LIB = r'F:\Vesna\lib'
OUT = r'F:\Vesna\src\cpp\embedded_lib.h'
DELIM = 'VESLIB_1_7'

names = sorted(f for f in os.listdir(LIB) if f.endswith('.ves'))
lines = ['#pragma once', '// Auto-generated by tools/embed_lib.py — do not edit by hand.',
         '#include <string>', 'namespace vesna {']
for n in names:
    src = io.open(os.path.join(LIB, n), encoding='utf-8').read()
    if src.endswith('\n'):
        src = src[:-1]
    assert ')%s"' % DELIM not in src, 'delimiter conflict in ' + n
    var = 'kEmbeddedLib_' + re.sub(r'[^A-Za-z0-9]', '_', n[:-4])
    lines.append('static const std::string %s = R"%s(%s)%s";' % (var, DELIM, src, DELIM))
lines.append('inline std::string embeddedLib(const std::string& name) {')
for n in names:
    var = 'kEmbeddedLib_' + re.sub(r'[^A-Za-z0-9]', '_', n[:-4])
    lines.append('    if (name == "%s") return %s;' % (n, var))
lines.append('    return "";')
lines.append('}')  # namespace
lines.append('}')
io.open(OUT, 'w', encoding='utf-8', newline='\n').write('\n'.join(lines) + '\n')
print('generated', OUT, '->', len(names), 'modules,', os.path.getsize(OUT), 'bytes')
